const EXTRA_PRODUCTS = [
  { id: 16, name: 'Ruby Wrap Dress', category: 'Dresses', price: 2999, image: 'assets/product-016.jpg', badge: 'New' },
  { id: 17, name: 'Teal Bamboo Jumpsuit', category: 'Jumpsuits', price: 2799, image: 'assets/product-017.jpg', badge: '' },
  { id: 18, name: 'Amber Knit Cardigan', category: 'Knitwear', price: 2499, image: 'assets/product-018.jpg', badge: '' },
  { id: 19, name: 'Plum Velvet Blazer', category: 'Outerwear', price: 2999, image: 'assets/product-019.jpg', badge: 'Premium' },
  { id: 20, name: 'Citrus Linen Shirt', category: 'Shirts', price: 1899, image: 'assets/product-020.jpg', badge: 'New' },
  { id: 21, name: 'Ocean Wave Maxi', category: 'Dresses', price: 2999, image: 'assets/product-021.jpg', badge: '' },
  { id: 22, name: 'Blush Ruffle Top', category: 'Tops', price: 1699, image: 'assets/product-022.jpg', badge: 'Bestseller' },
  { id: 23, name: 'Forest Cargo Pants', category: 'Bottoms', price: 2199, image: 'assets/product-023.jpg', badge: '' },
  { id: 24, name: 'Midnight Silk Cami', category: 'Tops', price: 1599, image: 'assets/product-024.jpg', badge: '' },
  { id: 25, name: 'Peach Pleated Skirt', category: 'Skirts', price: 1999, image: 'assets/product-025.jpg', badge: 'New' },
  { id: 26, name: 'Ivory Cable Knit', category: 'Knitwear', price: 2699, image: 'assets/product-026.jpg', badge: '' },
  { id: 27, name: 'Copper Satin Slip', category: 'Dresses', price: 2399, image: 'assets/product-027.jpg', badge: '' },
  { id: 28, name: 'Jade Wrap Blouse', category: 'Tops', price: 1799, image: 'assets/product-028.jpg', badge: '' },
  { id: 29, name: 'Lilac Tiered Dress', category: 'Dresses', price: 2899, image: 'assets/product-029.jpg', badge: 'New' },
  { id: 30, name: 'Sand Linen Shorts', category: 'Bottoms', price: 1499, image: 'assets/product-030.jpg', badge: '' },
  { id: 31, name: 'Cherry Knit Polo', category: 'Knitwear', price: 1999, image: 'assets/product-031.jpg', badge: '' },
  { id: 32, name: 'Arctic Puffer Vest', category: 'Outerwear', price: 2999, image: 'assets/product-032.jpg', badge: 'Premium' },
  { id: 33, name: 'Mocha Wide Trousers', category: 'Bottoms', price: 2099, image: 'assets/product-033.jpg', badge: '' },
  { id: 34, name: 'Fuchsia Silk Top', category: 'Tops', price: 1899, image: 'assets/product-034.jpg', badge: 'Bestseller' },
  { id: 35, name: 'Olive Utility Jacket', category: 'Outerwear', price: 2799, image: 'assets/product-035.jpg', badge: '' },
];
